### ISSUE TITLE
Adding server to the QuakeJS Master server list

### ISSUE THREAD

**Issue by kwadroke** [treyyoder/quakejs-docker#15]
Is this Docker container able to register to the _master.quakejs.com_ MasterServer so it will show up in its list at http://quakejs.com?

I tried to add to autoexec.cfg via docker-compose.

autoexec.cfg
```
set sv_master1 "master.quakejs.com"
set dedicated 2
```

docker-compose.yaml
```
version: '2'
services:
    quakejs:
        container_name: quakejs
        environment:
            - SERVER=XX.XX.XX.XX
            - HTTP_PORT=8080
        ports:
            - '8080:80'
            - '27960:27960'
        image: 'treyyoder/quakejs:latest'
        volumes:
            - /home/docker/quakejs/server.cfg:/quakejs/base/baseq3/server.cfg
            - /home/docker/quakejs/autoexec.cfg:/quakejs/base/baseq3/autoexec.cfg
```

I think either the master server didn't like the information it was sending, as the list on the quakejs.com website went blank, or just my desktop was being slow.

**Comment by kwadroke** [comment]
I found some info from the upstream QuakeJS Git repo that I might be able to use. Will report back with my changes once I get fixed nailed down.

**Comment by Locustv2** [comment]
For this one you will need to modify this line: https://github.com/treyyoder/quakejs-docker/blob/1f25c4c2477d60cbd383af2b90ec3b9299024672/entrypoint.sh#L13

to `dedicated 2` for internet instead of LAN. Then if everything is configured properly including ports forwarding etc, your server should be shown on quakejs

**Comment by kwadroke** [comment]
I'm working on a way to do that without modifying the container.

**Comment by Locustv2** [comment]
What exactly is your plan?

**Comment by kwadroke** [comment]
Finally getting back to this.

I recently found out that you can override the EntryPoint in the docker container by using a docker-compose.yml file. 

```
version: '3'
services:
    quakejs:
        container_name: quakejs
        environment:
            - SERVER=XX.XX.XX.XX
            - HTTP_PORT=8080
        ports:
            - '8080:80'
            - '27960:27960'
        image: 'treyyoder/quakejs:latest'
        volumes:
            - /home/docker/quakejs/server.cfg:/quakejs/base/baseq3/server.cfg
            - /home/docker/quakejs/autoexec.cfg:/quakejs/base/baseq3/autoexec.cfg
            - /home/docker/quakejs/newentrypoint.sh:/quakejs/base/newentrypoint.sh
        entrypoint: ["/quakejs/base/newentrypoint.sh"]
```

with an minor change from entrypoint.sh to _newentrypoint.sh_ to a local file 
```
#!/bin/sh
cd /var/www/html
sed -i "s/quakejs/${SERVER}/g" index.html
sed -i "s/${SERVER}:80/${SERVER}:${HTTP_PORT}/g" index.html
/etc/init.d/apache2 start     
cd /quakejs
node build/ioq3ded.js +set fs_game baseq3 +exec server.cfg +set dedicated 1
```

Don't forget to `chmod +x newentrypoint.sh`

Haven't had a chance to test this yet, but it should work.

**Comment by jpcapone** [comment]
did you get a chance to test it out yet?   I get the error below when I tried it
standard_init_linux.go:228: exec user process caused: no such file or directory

**Comment by kwadroke** [comment]
So far this is working for me. Got it to register with QuakeJS and show up on the server list. Still need to test outside of my network.

You need to change the values under _environment_. They will be read for the _newentrypoint.sh_ script.

docker-compose.yml
```
version: '3'
services:
    quakejs:
        container_name: quakejs
        environment:
            - SERVER=127.0.0.1  # Chnage to your IP Address
            - HTTP_PORT=8080
            - MASTERSERVER=97.107.129.89   #master.quakejs.com did not resolve for me properly, using IP instead
            - SERVERNAME="MyQuakeJS Server"
            - RCONPASS="MyRCONPass01"
        ports:
            - '8080:80'
            - '27960:27960'
        image: 'treyyoder/quakejs:latest'
        volumes:
            - ./newentrypoint.sh:/quakejs/base/newentrypoint.sh
        entrypoint: ["/bin/bash","/quakejs/base/newentrypoint.sh"]
```

newentrypoint.sh
```sh
#!/bin/sh
echo Using New Entry Point script
cd /var/www/html
sed -i "s/quakejs/${SERVER}/g" index.html
sed -i "s/${SERVER}:80/${SERVER}:${HTTP_PORT}/g" index.html
/etc/init.d/apache2 start     
cd /quakejs
node build/ioq3ded.js +set fs_game baseq3 +exec server.cfg +set dedicated 2 +set sv_master1 "${MASTERSERVER}" +sv_hostname "${SERVERNAME}" +set rconpassword "${RCONPASS}"
```
