### ISSUE TITLE
Can't start docker because of "ECONNREFUSED 188.114.97.2:80"

### ISSUE THREAD

**Issue by Onion2222** [treyyoder/quakejs-docker#20]
Hello,
I'm trying to install quakejs-docker on a Debian 11 behind a proxy.
Unfortunately, when do `sudo -E docker compose up`, it failed because of this error:
```
x@xxx:~/quake$ export https_proxy=http://proxy:3128
x@xxx:~/quake$ export http_proxy=http://proxy:3128
x@xxx:~/quake$ sudo -E docker compose up
[+] Running 1/0
 ⠿ Container quakejs  Created                                                                                                                                                                             0.0s
Attaching to quakejs
quakejs  |  * Starting Apache httpd web server apache2
quakejs  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.25.0.2. Set the 'ServerName' directive globally to suppress this message
quakejs  |  * 
quakejs  | WARNING: using emscripten GL emulation. This is a collection of limited workarounds, do not expect it to work.
quakejs  | WARNING: using emscripten GL emulation unsafe opts. If weirdness happens, try -s GL_UNSAFE_OPTS=0
quakejs  | ioq3 1.36_GIT_4f7d7bf-2014-02-01 emscripten- Feb 23 2014
quakejs  | ----- FS_Startup -----
quakejs  | events.js:183
quakejs  |       throw er; // Unhandled 'error' event
quakejs  |       ^
quakejs  | 
quakejs  | Error: connect ECONNREFUSED 188.114.97.2:80
quakejs  |     at Object._errnoException (util.js:1022:11)
quakejs  |     at _exceptionWithHostPort (util.js:1044:20)
quakejs  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
quakejs exited with code 1
```
I also tried with curl to get to this IP:
```
x@xxx:~/quake$ sudo -E curl 188.114.97.2:80
error code: 1003
```
my `docker-compose.yml` :
```
version: '2'
services:
    quakejs:
        container_name: quakejs
        environment:
            - HTTP_PORT=8080
        ports:
            - '8080:80'
            - '27960:27960'
        image: 'treyyoder/quakejs:latest'
```

So I think the website is down and it's now impossible to download all the necessary file...
Is this correct ? Is there another way to download the files ?

Thanks a lot for your help !
