### ISSUE TITLE
Pi support

### ISSUE THREAD

**Issue by ChrisScottThomas** [treyyoder/quakejs-docker#8]
Hello!  First off, thanks for this, I'm having great fun smashing my kids into the ground!

Secondly, a tip for anyone who's looking, swapping the image base to `arm32v7/ubuntu:latest` allows you to host this on a Pi.  This has made it a lot better for me at home, as I can leave it up all the time rather than spawning it on a macbook.

Cheers!

**Comment by Ethergy** [comment]
@ChrisScottThomas Would you mind explaining how to do this?

**Comment by g0rge0us** [comment]
I guess the only option is to change the docker image, because this one "treyyoder/quakejs" does not support other tags than "latest" and is NOT compatible with ARM (neither 32 nor 64) architectures. 

The following stack/compose file is working for me on RPI4 (4GB RAM).
```
version: '2'
services:
    quakejs:
        container_name: quakejs
        environment:
            - HTTP_PORT=8282
            - SERVER=10.0.0.4 #your internal IP
        ports:
            - '8282:80'
            - '27960:27960'
        image: 'chrisscottthomas/quakejs:latest'
```
Good luck!
